### ISSUE TITLE
Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by elvismdev** [cosmith/loki-cordova-fs-adapter#1]
Hi,
I'm using this adapter in my [small project](https://github.com/elvismdev/WooReportApp) with Ionic and AngularJS  but it keeps dropping me this error in the console.

```javascript
Uncaught ReferenceError: module is not defined
```
![Error Screenshot](http://s23.postimg.org/bwh85kkp7/Selection_116.png)

I think I'm [including](https://github.com/elvismdev/WooReportApp/blob/master/www/index.html) everything correctly in the right order. Wondering if this could be a bug in the [loki-cordova-fs-adapter.js](https://github.com/cosmith/loki-cordova-fs-adapter/blob/master/bin/loki-cordova-fs-adapter.js) file?

Just wanted to make sure I'm not missing any detail or if this can brake any aspect for the right functionality of this adapter for Lokijs. Feel free to clone/fork [my project](https://github.com/elvismdev/WooReportApp) to test in case you need to.

Thank you.

**Comment by cosmith** [comment]
Hi, I'm not sure how this works with Ionic / Angular but the way I'm using it is by requiring the module directly (`require("./loki-cordova-fs-adapter")`) and not including it in my `index.html`.

You can still use it this way though, you just have to remove the last line of the js file 
```js
module.exports = LokiCordovaFSAdapter;
```

And you should have a global reference to `LokiCordovaFSAdapter` available.

Let me know if this works for you

**Comment by elvismdev** [comment]
Well yeah actually that's what I just did, commented the line and seems all is fine and working as expected, was just worried if that could break something under the hood without notice.

Anyways thanks for the quick response and this cool adapter!

Regards
