### ISSUE TITLE
can you add a package.json file to the root so it can be npm installed?

### ISSUE THREAD

**Issue by rockneverdies55** [cosmith/loki-cordova-fs-adapter#10]
Thanks for sharing this. Can you possibly add a `package.json` file so it can be installed by npm?

**Comment by cosmith** [comment]
Done, and published to npm: https://www.npmjs.com/package/loki-cordova-fs-adapter

Let me know if it works for you, it's the first time I try this.

**Comment by rockneverdies55** [comment]
Great, thank you. I haven't tested yours yet. Though, last night [I forked your project](https://github.com/rockneverdies55/loki-cordova-fs-adapter) to add a `package.json` myself . And it didn't work directly after adding `package.json`, I also had to comment out `module.exports` line at the end of `bin/loki-cordova-fs-adapter.js` file.  
I'll take a look at yours later.

**Comment by cosmith** [comment]
Ok I uncommented it too.

**Comment by rockneverdies55** [comment]
Thanks again. I'll confirm and get back to you.

**Comment by rockneverdies55** [comment]
This works fine, thanks.
