### ISSUE TITLE
IONIC 2 Compatible

### ISSUE THREAD

**Issue by Jheysoon** [cosmith/loki-cordova-fs-adapter#13]
Is this a ionic 2 compatible already ?

**Comment by techfort** [comment]
hey @Jheysoon i'm not an ionic expert, what is required for ionic 2 compatibility? LokiJS is pretty much framework/runtime agnostic.

**Comment by Jheysoon** [comment]
![error](https://cloud.githubusercontent.com/assets/8098903/20088113/0e234394-a5b9-11e6-85e7-00f5c0cd1dce.png)

Yeah lokijs is just fine the adapter is giving me a error like this.
