### ISSUE TITLE
Compiled JS file pollutes global scope

### ISSUE THREAD

**Issue by gudmundurh** [cosmith/loki-cordova-fs-adapter#4]
Hi guys – thanks for the good work!

The compiled JS file adds a handful of unwanted globals, such as _createClass and more Babel stuff, and the TAG constant. It also adds global "use strict", which enables strict mode everywhere.

Can you change the build script to fix this? I did at quick experiment myself, but I'm not familiar with Babel, and didn't succeed in fixing it quickly. I guess there should exist some Babel plugins for this.

(It would also be great if you referred babel and eslint from a local node_modules folder, and added them in package.json. More unwanted globals :smirk:)

**Comment by cosmith** [comment]
Hi, are you using with `require` or loading it in a `script` tag? The better way would be to use `require`, then your global namespace wouldn't be polluted.

To be able to do this you need to uncomment the last line here:
https://github.com/cosmith/loki-cordova-fs-adapter/blob/f073d72c5c7b6d03d95c3bead877db532bb3bde0/bin/loki-cordova-fs-adapter.js#L152

**Comment by gudmundurh** [comment]
Hi @cosmith – thanks for the reply. We're using it as-is in a script tag, as our bundling setup is rather old-fashioned right now. Kind of find it strange that Babel doesn't just take care of it, such as with an IIFE, regardless of the module/load setup.

**Comment by cosmith** [comment]
You can still use it with an IIFE I guess... shouldn't be too much work.

**Comment by gudmundurh** [comment]
No it’s easy – guess I’ll just do that then. Just hoped it could be incorporated in the build somehow.

**Comment by cosmith** [comment]
I tried wrapping the whole thing in an IIFE in the .es6 file but unfortunately even that doesn't work... the `"use strict"` statement and `_createClass` etc. end up outside of the IIFE in the compiled .js, so I don't know what else I can do except do it by hand.

Let me know if you find another solution!

**Comment by gudmundurh** [comment]
No problem – thanks. 

Perhaps I can just use the es6 file as an TypeScript file – we’re writing the app in TypeScript. If that works, I’ll write back and let you know.
