### ISSUE TITLE
Error: undefined is not an object (evaluating '_budgets.insert')

### ISSUE THREAD

**Issue by galcivar** [cosmith/loki-cordova-fs-adapter#6]
Hi!
I am trying to run the following:

```
function addBudget(budget) {
_budgets.insert(budgets);
_db.saveDatabase;
return budget.$loki;
};
```

Now in Android it does work, but when I tried to run it in IOS I get the following error:

> Error: undefined is not an object (evaluating '_budgets.insert')

I did a console.log(budget) before _budgets.insert(budgets); and budget is indeed an object.

Regarding the config.xml I only added:
`<preference name="AndroidPersistentFileLocation" value="Compatibility"/>`

Is there something I am missing?

Thanks

**Comment by cosmith** [comment]
This is probably an error that is not related to this adapter.

Your error is stating that the `insert` method on `_budgets` doesn't exist, not that `budget` is `undefined`.

Maybe try logging `_budgets` inside this function?

**Comment by galcivar** [comment]
logged to: undefined

You're right, the `_budgets` is not being defined in iOS (weirdly enough it is working in Android).

Will run further tests, thanks!

**Comment by lfreneda** [comment]
@galcivar same issue here, what should I do to correct?

**Comment by galcivar** [comment]
@lfreneda really can't remember but it was not related to the adapter but to something else, thus I closed it

**Comment by lfreneda** [comment]
@galcivar ok, thanks sz
