### ISSUE TITLE
Registering it into Bower?

### ISSUE THREAD

**Issue by moQuez** [cosmith/loki-cordova-fs-adapter#7]
Hey there... 

I was wondering if there is any chance for you to register this adapter onto bower since I'd really love to have it up-to-date automatically with it.

Thanks in advance,

**Comment by cosmith** [comment]
Hi, I've never used bower before so I'm not sure how the whole thing works but I added the `bower.json` and registered the component to bower.io... Can you try and let me know if it works? I think there might be an issue with module loading.
