### ISSUE TITLE
Saving single collection instead of the whole database?

### ISSUE THREAD

**Issue by kerosin** [cosmith/loki-cordova-fs-adapter#8]
Hey,

Imagine using around 20 collections with some heavy ones (like 4MB JSON data or so).
Is there a way to save a single collection instead of dumping the whole database? There might be changes that only affect a single collection. Or what is the sense of collections? Creating 20 databases seems to be wrong.

Thanks in advance

**Comment by cosmith** [comment]
Hi! You should probably ask about this directly to the LokiJS guys... I use Loki with a single collection right now so I'm not sure what the idea behind them is exactly.

**Comment by kerosin** [comment]
Thanks, created a lokijs [ticket #341](https://github.com/techfort/LokiJS/issues/341).
